# Generated by Django 4.2.7 on 2023-11-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nurses',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('mi', models.CharField(max_length=1)),
                ('lname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone_num', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('ssn', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('mi', models.CharField(max_length=1)),
                ('lname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('race', models.CharField(max_length=2)),
                ('occupation', models.CharField(max_length=50)),
                ('medical_history', models.TextField(max_length=500)),
                ('phone_num', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccines',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('co_name', models.CharField(max_length=100)),
                ('doses_req', models.IntegerField(default=1)),
                ('description', models.TextField(max_length=500)),
                ('available', models.IntegerField(default=0)),
                ('on_hold', models.IntegerField(default=0)),
            ],
        ),
    ]
