# Generated by Django 4.2.7 on 2023-11-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccines',
            name='vax_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nurses',
            name='employee_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vaccines',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
