# Generated by Django 4.2.7 on 2023-11-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_nurses_employee_id_alter_vaccines_vax_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurses',
            name='mi',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
