# Generated by Django 4.2.7 on 2023-11-28 00:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_nurses_mi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse_Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot', models.TimeField()),
                ('employee_id', models.IntegerField(default=0)),
                ('num_patients', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot', models.TimeField()),
                ('ssn', models.CharField(max_length=9)),
                ('employee_id', models.IntegerField(default=0)),
                ('vax_id', models.IntegerField()),
                ('vax_dose', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('slot', models.TimeField(primary_key=True, serialize=False)),
                ('num_patients', models.IntegerField(default=0)),
                ('num_nurses', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='nurses',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(21)]),
        ),
        migrations.AlterField(
            model_name='patients',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='patients',
            name='medical_history',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='vaccines',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
