# Generated by Django 4.2.7 on 2023-11-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_nurse_schedule_patient_schedule_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='slot',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
