# Generated by Django 4.2.7 on 2023-11-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_schedule_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurse_schedule',
            old_name='schedule_id',
            new_name='N_schedule_id',
        ),
        migrations.RenameField(
            model_name='patient_schedule',
            old_name='schedule_id',
            new_name='P_schedule_id',
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_id',
            field=models.AutoField(default=-1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot',
            field=models.DateTimeField(),
        ),
    ]
