# Generated by Django 4.2.7 on 2023-11-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_schedule_id_nurse_schedule_n_schedule_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
