from django.urls import path
from .views import (
    VaccinesView, 
    NursesView, 
    PatientsView, 
    ScheduleView,
    PatientScheduleView,
    NurseScheduleView,
    CreateVaccinesView,
    CreateNursesView,
    CreatePatientsView,
    CreateScheduleView,
    CreatePatientScheduleView,
    CreateNurseScheduleView,
    DeleteVaccinesView,
    DeleteNurseView,
    DeletePatientsView,
    DeleteScheduleView,
    DeletePatientScheduleView,
    DeleteNurseScheduleView,
    UpdateVaccinesView,
    UpdateNurseView,
    UpdatePatientsView,
    UpdateScheduleView,
    UpdatePatientScheduleView,
    UpdateNurseScheduleView,
    )

urlpatterns = [
    path('vaccines', VaccinesView.as_view()),
    path('nurses', NursesView.as_view()),
    path('patients', PatientsView.as_view()),
    path('schedule', ScheduleView.as_view()),
    path('patient-schedule', PatientScheduleView.as_view()),
    path('nurse-schedule', NurseScheduleView.as_view()),
    path('add-vaccine', CreateVaccinesView.as_view()),
    path('add-nurse', CreateNursesView.as_view()),
    path('add-patient', CreatePatientsView.as_view()),
    path('add-schedule', CreateScheduleView.as_view()),
    path('add-patient-schedule', CreatePatientScheduleView.as_view()),
    path('add-nurse-schedule', CreateNurseScheduleView.as_view()),
    path('del-vaccine/<int:pk>/', DeleteVaccinesView.as_view()),
    path('del-nurse/<int:pk>/', DeleteNurseView.as_view()),
    path('del-patient/<int:pk>/', DeletePatientsView.as_view()),
    path('del-schedule/<int:pk>/', DeleteScheduleView.as_view()),
    path('del-patient-schedule/<int:pk>/', DeletePatientScheduleView.as_view()),
    path('del-nurse-schedule/<int:pk>/', DeleteNurseScheduleView.as_view()),
    path('update-vaccine/<int:pk>/', UpdateVaccinesView.as_view()),
    path('update-nurse/<int:pk>/', UpdateNurseView.as_view()),
    path('update-patient/<int:pk>/', UpdatePatientsView.as_view()),
    path('update-schedule/<int:pk>/', UpdateScheduleView.as_view()),
    path('update-patient-schedule/<int:pk>/', UpdatePatientScheduleView.as_view()),
    path('update-nurse-schedule/<int:pk>/', UpdateNurseScheduleView.as_view()),
]